sagebase:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID', 'sagebase') }}"
      dataset: sagebase_vault
      threads: 4
      timeout_seconds: 300
      location: asia-northeast1
      priority: interactive
      retries: 1
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID', 'sagebase') }}"
      dataset: sagebase_vault
      threads: 4
      timeout_seconds: 300
      location: asia-northeast1
      priority: interactive
      retries: 1
    ci:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID', 'sagebase') }}"
      dataset: sagebase_vault
      threads: 4
      timeout_seconds: 300
      location: asia-northeast1
      priority: interactive
      retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '') }}"
