-- Generated from database on 2026-02-15 01:55:09
-- parliamentary_groups seed data
-- Updated: 2026-02-25 Issue #1232 chamberカラム追加・衆参会派分離

INSERT INTO parliamentary_groups (name, governing_body_id, url, description, is_active, political_party_id, chamber) VALUES
-- 京都府京都市 (市町村) - chamber = ''
(' 日本共産党京都市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://cpgkyoto.jp/', NULL, true, (SELECT id FROM political_parties WHERE name = '日本共産党'), ''),
('公明党京都市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www.komeito-kyotocity.com/#member', NULL, true, (SELECT id FROM political_parties WHERE name = '公明党'), ''),
('改新京都', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/kaishinkyoto.html', NULL, true, NULL, ''),
('民主・市民フォーラム京都市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/minsyu-kyoto.html', NULL, true, NULL, ''),
('無所属', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/mushozoku.html', NULL, true, NULL, ''),
('維新・京都・国民市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/ishin-kyoto-kokumin.html', NULL, true, NULL, ''),
('自由民主党京都市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://jimin-kyoto.jp/member_list/', NULL, true, (SELECT id FROM political_parties WHERE name = '自由民主党'), ''),

-- 国会 (国) - 衆議院 歴史的会派（is_active = false）
('21世紀クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, NULL, '衆議院'),
('おおさか維新の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '日本維新の会'), '衆議院'),
('さきがけ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '新党さきがけ'), '衆議院'),
('たちあがれ日本', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = 'たちあがれ日本'), '衆議院'),
('みんなの党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = 'みんなの党'), '衆議院'),
('保守党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '保守党'), '衆議院'),
('保守新党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '保守新党'), '衆議院'),
('公明党・改革クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '公明党'), '衆議院'),
('国民の生活が第一・きづな', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '生活の党'), '衆議院'),
('国民新党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '国民新党'), '衆議院'),
('国民新党・そうぞう・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '国民新党'), '衆議院'),
('国民新党・大地・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '国民新党'), '衆議院'),
('国民新党・新党日本', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '国民新党'), '衆議院'),
('国民新党・日本・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '国民新党'), '衆議院'),
('国民新党・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '国民新党'), '衆議院'),
('国民新党・無所属会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '国民新党'), '衆議院'),
('国益と国民の生活を守る会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, NULL, '衆議院'),
('太陽党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '太陽党'), '衆議院'),
('希望の党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '希望の党'), '衆議院'),
('希望の党・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '希望の党'), '衆議院'),
('平和・改革', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '公明党'), '衆議院'),
('改革無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, NULL, '衆議院'),
('改革結集の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, NULL, '衆議院'),
('新党きづな', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '新党きづな'), '衆議院'),
('新党さきがけ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '新党さきがけ'), '衆議院'),
('新党大地・真民主', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '新党大地'), '衆議院'),
('新進党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '新進党'), '衆議院'),
('日本維新の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '日本維新の会'), '衆議院'),
('日本維新の会・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '日本維新の会'), '衆議院'),
('未来日本', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, NULL, '衆議院'),
('次世代の党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '次世代の党'), '衆議院'),
('民主・維新・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '民主党'), '衆議院'),
('民主党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '民主党'), '衆議院'),
('民主党・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '民主党'), '衆議院'),
('民主党・無所属クラブ・国民新党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '民主党'), '衆議院'),
('民友連', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '民主党'), '衆議院'),
('民進党・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '民主党'), '衆議院'),
('減税日本・平安', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '減税日本'), '衆議院'),
('無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '無所属'), '衆議院'),
('生活の党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '生活の党'), '衆議院'),
('生活の党と山本太郎となかまたち', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '生活の党'), '衆議院'),
('社会保障を立て直す国民会議', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, NULL, '衆議院'),
('社会民主党・市民連合', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '社会民主党'), '衆議院'),
('立憲民主・国民・社保・無所属フォーラム', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '立憲民主党'), '衆議院'),
('立憲民主党・市民クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '立憲民主党'), '衆議院'),
('立憲民主党・無所属フォーラム', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '立憲民主党'), '衆議院'),
('立憲民主党・社民・無所属', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '立憲民主党'), '衆議院'),
('結いの党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '結いの党'), '衆議院'),
('維新の党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '日本維新の会'), '衆議院'),
('自由党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '自由党'), '衆議院'),
('自由民主党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '自由民主党'), '衆議院'),
('自由民主党・改革クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '自由民主党'), '衆議院'),
('自由民主党・無所属会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, (SELECT id FROM political_parties WHERE name = '自由民主党'), '衆議院'),
('２１世紀', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, false, NULL, '衆議院'),

-- 現行会派（is_active = true）- 衆議院
('れいわ新選組', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = 'れいわ新選組'), '衆議院'),
('チームみらい・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '衆議院219回次〜', true, NULL, '衆議院'),
('公明党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '公明党'), '衆議院'),
('参政党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '参政党'), '衆議院'),
('国民民主党・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '国民民主党'), '衆議院'),
('改革の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '衆議院219回次〜', true, NULL, '衆議院'),
('日本保守党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本保守党'), '衆議院'),
('日本共産党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本共産党'), '衆議院'),
('日本維新の会・教育無償化を実現する会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本維新の会'), '衆議院'),
('有志の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL, '衆議院'),
('減税保守こども', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL, '衆議院'),
('無所属', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '無所属'), '衆議院'),
('立憲民主党・無所属', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '立憲民主党'), '衆議院'),
('自由民主党・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '自由民主党'), '衆議院'),

-- 現行会派（is_active = true）- 参議院（kaiha.json/giin.jsonより）
('各派に属しない議員', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, NULL, '参議院'),
('国民民主党・新緑風会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '国民民主党'), '参議院'),
('沖縄の風', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '沖縄の風'), '参議院'),
('社会民主党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '社会民主党'), '参議院'),
('立憲民主・無所属', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '立憲民主党'), '参議院'),

-- 参議院の衆議院同名会派（Issue #1232で追加: chamberで衝突回避）
('自由民主党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '自由民主党'), '参議院'),
('公明党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '公明党'), '参議院'),
('日本共産党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '日本共産党'), '参議院'),
('れいわ新選組', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = 'れいわ新選組'), '参議院'),
('日本維新の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '日本維新の会'), '参議院'),
('参政党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '参政党'), '参議院'),
('日本保守党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '日本保守党'), '参議院'),
('無所属', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, '参議院', true, (SELECT id FROM political_parties WHERE name = '無所属'), '参議院')
ON CONFLICT (name, governing_body_id, chamber) DO UPDATE SET url = EXCLUDED.url, description = EXCLUDED.description, is_active = EXCLUDED.is_active, political_party_id = EXCLUDED.political_party_id;

-- シーケンスリセット（IDを明示指定していないためON CONFLICTで既存IDが使われるが、新規INSERTに備えてリセット）
SELECT setval('parliamentary_groups_id_seq', COALESCE((SELECT MAX(id) FROM parliamentary_groups), 0) + 1, false);
