-- Generated from database on 2026-02-14 09:59:39
-- parliamentary_groups seed data

INSERT INTO parliamentary_groups (name, governing_body_id, url, description, is_active, political_party_id) VALUES
-- 京都府京都市 (市町村)
(' 日本共産党京都市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://cpgkyoto.jp/', NULL, true, (SELECT id FROM political_parties WHERE name = '日本共産党')),
('公明党京都市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www.komeito-kyotocity.com/#member', NULL, true, (SELECT id FROM political_parties WHERE name = '公明党')),
('改新京都', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/kaishinkyoto.html', NULL, true, NULL),
('民主・市民フォーラム京都市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/minsyu-kyoto.html', NULL, true, NULL),
('無所属', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/mushozoku.html', NULL, true, NULL),
('維新・京都・国民市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/ishin-kyoto-kokumin.html', NULL, true, NULL),
('自由民主党京都市会議員団', (SELECT id FROM governing_bodies WHERE name = '京都府京都市' AND type = '市町村'), 'https://jimin-kyoto.jp/member_list/', NULL, true, (SELECT id FROM political_parties WHERE name = '自由民主党')),

-- 国会 (国)
('21世紀クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('おおさか維新の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本維新の会')),
('さきがけ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('たちあがれ日本', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('みんなの党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = 'みんなの党')),
('れいわ新選組', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = 'れいわ新選組')),
('保守党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('保守新党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('公明党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '公明党')),
('公明党・改革クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '公明党')),
('参政党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '参政党')),
('国民の生活が第一・きづな', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('国民新党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('国民新党・そうぞう・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('国民新党・大地・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('国民新党・新党日本', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('国民新党・日本・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('国民新党・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('国民新党・無所属会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('国民民主党・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '国民民主党')),
('国益と国民の生活を守る会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('太陽党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('希望の党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('希望の党・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('平和・改革', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('改革無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('改革結集の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('新党きづな', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('新党さきがけ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('新党大地・真民主', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('新進党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('日本保守党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('日本共産党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本共産党')),
('日本維新の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本維新の会')),
('日本維新の会・教育無償化を実現する会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本維新の会')),
('日本維新の会・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本維新の会')),
('有志の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('未来日本', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('次世代の党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('民主・維新・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('民主党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('民主党・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('民主党・無所属クラブ・国民新党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('民友連', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('民進党・無所属クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('減税保守こども', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('減税日本・平安', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '減税日本')),
('無所属', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '無所属')),
('無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '無所属')),
('生活の党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('生活の党と山本太郎となかまたち', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('社会保障を立て直す国民会議', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('社会民主党・市民連合', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '社会民主党')),
('立憲民主・国民・社保・無所属フォーラム', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '立憲民主党')),
('立憲民主党・市民クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '立憲民主党')),
('立憲民主党・無所属', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '立憲民主党')),
('立憲民主党・無所属フォーラム', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '立憲民主党')),
('立憲民主党・社民・無所属', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '立憲民主党')),
('結いの党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('維新の党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '日本維新の会')),
('自由党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL),
('自由民主党', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '自由民主党')),
('自由民主党・改革クラブ', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '自由民主党')),
('自由民主党・無所属の会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '自由民主党')),
('自由民主党・無所属会', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, (SELECT id FROM political_parties WHERE name = '自由民主党')),
('２１世紀', (SELECT id FROM governing_bodies WHERE name = '国会' AND type = '国'), NULL, NULL, true, NULL)
ON CONFLICT (name, governing_body_id) DO UPDATE SET url = EXCLUDED.url, description = EXCLUDED.description, is_active = EXCLUDED.is_active, political_party_id = EXCLUDED.political_party_id;
