-- Parliamentary Groups Seed Data
-- Generated from current database
-- 国会の議員団はgian.csv（SmartNews）の議案提出会派カラムから抽出
-- political_party_id: 議員団名の主要政党から推測して紐付け（対応する政党がない場合はNULL）

INSERT INTO parliamentary_groups (id, name, governing_body_id, url, description, is_active, political_party_id) VALUES
    -- 京都市会（governing_body_id=88）
    (1, ' 日本共産党京都市会議員団', 88, 'https://cpgkyoto.jp/', NULL, true, 9),
    (2, '公明党京都市会議員団', 88, 'https://www.komeito-kyotocity.com/#member', NULL, true, 5),
    (3, '改新京都', 88, 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/kaishinkyoto.html', NULL, true, NULL),
    (4, '民主・市民フォーラム京都市会議員団', 88, 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/minsyu-kyoto.html', NULL, true, NULL),
    (5, '無所属', 88, 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/mushozoku.html', NULL, true, NULL),
    (6, '維新・京都・国民市会議員団', 88, 'https://www2.city.kyoto.lg.jp/shikai/meibo/kaiha/ishin-kyoto-kokumin.html', NULL, true, NULL),
    (7, '自由民主党京都市会議員団', 88, 'https://jimin-kyoto.jp/member_list/', NULL, true, 15),
    -- 国会（governing_body_id=1）
    -- political_party_id: 3=みんなの党, 4=れいわ新選組, 5=公明党, 6=参政党, 7=国民民主党,
    --   9=日本共産党, 10=日本維新の会, 11=減税日本, 12=無所属, 13=社会民主党, 14=立憲民主党, 15=自由民主党
    (8, '自由民主党・無所属の会', 1, NULL, NULL, true, 15),
    (9, '立憲民主党・無所属', 1, NULL, NULL, true, 14),
    (10, '21世紀クラブ', 1, NULL, NULL, true, NULL),
    (11, 'おおさか維新の会', 1, NULL, NULL, true, 10),
    (12, 'さきがけ', 1, NULL, NULL, true, NULL),
    (13, 'たちあがれ日本', 1, NULL, NULL, true, NULL),
    (14, 'みんなの党', 1, NULL, NULL, true, 3),
    (15, 'れいわ新選組', 1, NULL, NULL, true, 4),
    (16, '保守党', 1, NULL, NULL, true, NULL),
    (17, '保守新党', 1, NULL, NULL, true, NULL),
    (18, '公明党', 1, NULL, NULL, true, 5),
    (19, '公明党・改革クラブ', 1, NULL, NULL, true, 5),
    (20, '参政党', 1, NULL, NULL, true, 6),
    (21, '国民の生活が第一・きづな', 1, NULL, NULL, true, NULL),
    (22, '国民新党', 1, NULL, NULL, true, NULL),
    (23, '国民新党・そうぞう・無所属の会', 1, NULL, NULL, true, NULL),
    (24, '国民新党・大地・無所属の会', 1, NULL, NULL, true, NULL),
    (25, '国民新党・新党日本', 1, NULL, NULL, true, NULL),
    (26, '国民新党・日本・無所属の会', 1, NULL, NULL, true, NULL),
    (27, '国民新党・無所属の会', 1, NULL, NULL, true, NULL),
    (28, '国民新党・無所属会', 1, NULL, NULL, true, NULL),
    (29, '国民民主党・無所属クラブ', 1, NULL, NULL, true, 7),
    (30, '国益と国民の生活を守る会', 1, NULL, NULL, true, NULL),
    (31, '太陽党', 1, NULL, NULL, true, NULL),
    (32, '希望の党', 1, NULL, NULL, true, NULL),
    (33, '希望の党・無所属クラブ', 1, NULL, NULL, true, NULL),
    (34, '平和・改革', 1, NULL, NULL, true, NULL),
    (35, '改革無所属の会', 1, NULL, NULL, true, NULL),
    (36, '改革結集の会', 1, NULL, NULL, true, NULL),
    (37, '新党きづな', 1, NULL, NULL, true, NULL),
    (38, '新党さきがけ', 1, NULL, NULL, true, NULL),
    (39, '新党大地・真民主', 1, NULL, NULL, true, NULL),
    (40, '新進党', 1, NULL, NULL, true, NULL),
    (41, '日本保守党', 1, NULL, NULL, true, NULL),
    (42, '日本共産党', 1, NULL, NULL, true, 9),
    (43, '日本維新の会', 1, NULL, NULL, true, 10),
    (44, '日本維新の会・教育無償化を実現する会', 1, NULL, NULL, true, 10),
    (45, '日本維新の会・無所属の会', 1, NULL, NULL, true, 10),
    (46, '有志の会', 1, NULL, NULL, true, NULL),
    (47, '未来日本', 1, NULL, NULL, true, NULL),
    (48, '次世代の党', 1, NULL, NULL, true, NULL),
    (49, '民主・維新・無所属クラブ', 1, NULL, NULL, true, NULL),
    (50, '民主党', 1, NULL, NULL, true, NULL),
    (51, '民主党・無所属クラブ', 1, NULL, NULL, true, NULL),
    (52, '民主党・無所属クラブ・国民新党', 1, NULL, NULL, true, NULL),
    (53, '民友連', 1, NULL, NULL, true, NULL),
    (54, '民進党・無所属クラブ', 1, NULL, NULL, true, NULL),
    (55, '減税保守こども', 1, NULL, NULL, true, NULL),
    (56, '減税日本・平安', 1, NULL, NULL, true, 11),
    (57, '無所属', 1, NULL, NULL, true, 12),
    (58, '無所属の会', 1, NULL, NULL, true, 12),
    (59, '生活の党', 1, NULL, NULL, true, NULL),
    (60, '生活の党と山本太郎となかまたち', 1, NULL, NULL, true, NULL),
    (61, '社会保障を立て直す国民会議', 1, NULL, NULL, true, NULL),
    (62, '社会民主党・市民連合', 1, NULL, NULL, true, 13),
    (63, '立憲民主・国民・社保・無所属フォーラム', 1, NULL, NULL, true, 14),
    (64, '立憲民主党・市民クラブ', 1, NULL, NULL, true, 14),
    (65, '立憲民主党・無所属フォーラム', 1, NULL, NULL, true, 14),
    (66, '立憲民主党・社民・無所属', 1, NULL, NULL, true, 14),
    (67, '結いの党', 1, NULL, NULL, true, NULL),
    (68, '維新の党', 1, NULL, NULL, true, 10),
    (69, '自由党', 1, NULL, NULL, true, NULL),
    (70, '自由民主党', 1, NULL, NULL, true, 15),
    (71, '自由民主党・改革クラブ', 1, NULL, NULL, true, 15),
    (72, '自由民主党・無所属会', 1, NULL, NULL, true, 15),
    (73, '２１世紀', 1, NULL, NULL, true, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    governing_body_id = EXCLUDED.governing_body_id,
    url = EXCLUDED.url,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    political_party_id = EXCLUDED.political_party_id;

-- Reset sequence to max id + 1 (Issue #1036)
SELECT setval('parliamentary_groups_id_seq',
    COALESCE((SELECT MAX(id) FROM parliamentary_groups), 0) + 1, false);
