-- Generated from database on 2026-02-15 01:55:09
-- political_parties seed data

INSERT INTO political_parties (name, members_list_url) VALUES
('(幸福実現党)', NULL),
('(幸福実現党）', NULL),
('(日本新党)', NULL),
('(日本維新の会)', NULL),
('(無所属)', NULL),
('(無所属）', NULL),
('(無投票）', NULL),
('(自由民主党)', NULL),
('(長野県を日本一好景気にする会)', NULL),
('NHKと裁判してる党
弁護士法72条違反で', NULL),
('NHK党', 'https://www.syoha.jp/%E5%85%9A%E5%BD%B9%E5%93%A1-%E8%AD%B0%E5%93%A1/'),
('[幸福実現党]', NULL),
('[無所属]', NULL),
('あべ  ひろき', NULL),
('その他', NULL),
('みんなでつくる党', NULL),
('みんなの党', NULL),
('れいわ新選組', 'https://reiwa-shinsengumi.com/member/'),
('公明', NULL),
('公明党', 'https://www.komei.or.jp/member/'),
('参政党', 'https://sanseito.jp/2020/member/'),
('国民新党', NULL),
('国民民主党', 'https://new-kokumin.jp/member'),
('大阪維新の会', 'https://oneosaka.jp/member/'),
('宮内  ひでき', NULL),
('小里　やすひろ', NULL),
('希望の党', NULL),
('幸福実現党', NULL),
('改革クラブ', NULL),
('改革未来党', NULL),
('新党くにもり', NULL),
('新党大地', NULL),
('新党日本', NULL),
('日本保守党', NULL),
('日本共産党', 'https://www.jcp.or.jp/giin/'),
('日本成功党', NULL),
('日本未来の党', NULL),
('日本維新', NULL),
('日本維新の会', 'https://o-ishin.jp/member/'),
('日本維新の会(新)', NULL),
('本人', NULL),
('森本  しんた
ろう', NULL),
('次世代の党', NULL),
('民　主　党', NULL),
('民主党', NULL),
('減税日本', 'http://genzeinippon.com/koho/'),
('無　所　属', NULL),
('無所属', NULL),
('生活の党', NULL),
('社会民主党', 'https://sdp.or.jp/local-assembly/'),
('社民党', NULL),
('立憲民主党', 'https://cdp-japan.jp/members/all'),
('立憲民主党(前)', NULL),
('竹うち  信
昭', NULL),
('維新の党', NULL),
('自由民主党', 'https://www.jimin.jp/member/search/'),
('自由民主党(前)', NULL),
('諸派', NULL),
('都民ファーストの会', 'https://tomin1st.jp/#Members'),
('野間　たけし', NULL),
('（みらい党）', NULL),
('（アイヌ民族党）', NULL),
('（フェア党）', NULL),
('（世界経済共同体党）', NULL),
('（二十一世紀日本維新会）', NULL),
('（労働者党）', NULL),
('（安楽死党）', NULL),
('（幸福実現党鹿児島県本部）', NULL),
('（幸福実現党）', NULL),
('（当たり前党）', NULL),
('（新党憲法９条）', NULL),
('（新党日本）', NULL),
('（日本保守党）', NULL),
('（森海党）', NULL),
('（減税日本）', NULL),
('（無所属)', NULL),
('（無所属）', NULL),
('（犬丸勝子と共和党）', NULL),
('（自由民主党）', NULL),
('（議員報酬ゼロを実現する会）', NULL),
('（都政を改革する会）', NULL),
('ＮＨＫと裁判してる党
弁護士法７２条違反で', NULL),
-- 歴史的政党（会派マッピング用に追加 Issue #1231）
('保守党', NULL),
('保守新党', NULL),
('新党さきがけ', NULL),
('新進党', NULL),
('太陽党', NULL),
('自由党', NULL),
('結いの党', NULL),
('新党きづな', NULL),
('たちあがれ日本', NULL),
('沖縄の風', NULL)
ON CONFLICT (name) DO NOTHING;
